### ISSUE TITLE
Email recollection

### ISSUE THREAD

**Issue by rcqx** [yycoss/yyctech#14]
Set an email recollection form using air table or a similar service that helps us gather subscribers for a future newsletter.

The link to the form can be provided after the user clicks in the "Stay in the loop" hero CTA and also can be displayed in the /newsletter route (temporally ofc)

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implemented an email collection form using Airtable for the newsletter subscription. Modified the hero CTA to link to the newsletter page and updated the newsletter page with the form.

You can review changes in this commit: https://github.com/lattaai13/yycoss-yyctech-14/commit/a1ef94baf824ec2561c462299f66ba69d217b693.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by rcqx** [comment]
Done
